# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
parameters:
- name: testProxyAgent
  type: boolean
  displayName: Test Proxy Agent
  default: true

# Targets
- name: win_x64
  type: boolean
  displayName: Windows (x64)
  default: true
- name: win_x86
  type: boolean
  displayName: Windows (x86)
  default: true
- name: linux_x64
  type: boolean
  displayName: Linux (x64)
  default: true
- name: linux_arm
  type: boolean
  displayName: Linux (ARM)
  default: false
- name: linux_arm64
  type: boolean
  displayName: Linux (ARM64)
  default: false
- name: alpine_x64
  type: boolean
  displayName: Alpine (x64)
  default: true
- name: alpine_arm64
  type: boolean
  displayName: Alpine (ARM64)
  default: true
- name: macOS_x64
  type: boolean
  displayName: macOS (x64)
  default: true
- name: macOS_arm64
  type: boolean
  displayName: macOS (ARM64)
  default: true

pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - 'docs/*'

extends:
  template: /.azure-pipelines/pipeline.yml@self
  parameters:
    publishArtifacts: ${{ ne(variables['Build.Reason'], 'PullRequest') }}
    buildAlternatePackage: false
    testProxyAgent: ${{ parameters.testProxyAgent }}
    win_x64: ${{ parameters.win_x64 }}
    win_x86: ${{ parameters.win_x86 }}
    linux_x64: ${{ parameters.linux_x64 }}
    linux_arm: ${{ parameters.linux_arm }}
    linux_arm64: ${{ parameters.linux_arm64 }}
    alpine_x64: ${{ parameters.alpine_x64 }}
    alpine_arm64: ${{ parameters.alpine_arm64 }}
    macOS_x64: ${{ parameters.macOS_x64 }}
    macOS_arm64: ${{ parameters.macOS_arm64 }}
