name: Help needed
description: Raise a question
title: "[Question]: "
labels: ["helpwanted"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to raise a question
  - type: markdown
    attributes:
      value: |
        ## Having issue with Tasks?
        Log an issue at [Azure-Pipelines-Tasks](https://github.com/Microsoft/azure-pipelines-tasks). It contains all of the in-box tasks we ship with Azure-Pipelines/VSTS/TFS. If you're having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue there.
  - type: textarea
    id: what-happened
    attributes:
      label: Describe your question
      placeholder: Put your question here.
    validations:
      required: true
  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: Specify the agent version and operation system version
      placeholder: Azure DevOps version 2.100.1 / Windows 10
    validations:
      required: true
  - type: checkboxes
    id: environment-type
    attributes:
      label: Environment type (Please select at least one enviroment where you face this issue)
      options:
        - label: Self-Hosted
        - label: Microsoft Hosted
        - label: VMSS Pool
        - label: Container
  - type: dropdown
    id: azure-devops-type
    attributes:
      label: Azure DevOps Server type
      options:
        - dev.azure.com (formerly visualstudio.com)
        - Azure DevOps Server (Please specify exact version in the textbox below)
    validations:
      required: true
  - type: input
    id: operation-system
    attributes:
      label: Operation system
      placeholder: Windows 11, Ubuntu 20.04...
  - type: input
    id: version-control-type
    attributes:
      label: Version controll system
  - type: input
    id: azure-devops-server-datails
    attributes:
      label: Azure DevOps Server Version (if applicable)
      placeholder: Azure DevOps Server 2019.1
