parameters:
- name: preBuildStages
  type: stageList
  default: []
- name: postBuildStages
  type: stageList
  default: []
- name: componentDetection
  type: boolean
  default: false
- name: test
  type: boolean
  default: true
- name: sign
  type: boolean
  default: false
- name: publishArtifacts
  type: boolean
  default: false
- name: buildAlternatePackage
  type: boolean
  default: true
- name: branch
  type: string
  default: ''
- name: skipRhelRelease
  type: boolean
  default: true
- name: releaseRhelOnly
  type: boolean
  default: false

# Targets
- name: win_x64
  type: boolean
  default: true
- name: win_x86
  type: boolean
  default: true
- name: linux_x64
  type: boolean
  default: true
- name: linux_arm
  type: boolean
  default: true
- name: linux_arm64
  type: boolean
  default: true
- name: rhel6_x64
  type: boolean
  default: true
- name: macOS_x64
  type: boolean
  default: true

resources:
  containers:
  - container: dotnetcore_arm
    image: azpagentinfra/arm:latest
  - container: dotnetcore_centos6
    image: azpagentinfra/centos6:latest

stages:

- ${{ parameters.preBuildStages }}

- stage: build
  displayName: Build
  jobs:

  # Windows (x64)
  - ${{ if and(parameters.win_x64, not(parameters.releaseRhelOnly)) }}:
    - template: build-jobs.yml
      parameters:
        jobName: build_windows_x64
        displayName: Windows (x64)
        pool:
          vmImage: windows-2019
        os: win
        arch: x64
        branch: ${{ parameters.branch }}
        codeCoverage: true
        componentDetection: ${{ parameters.componentDetection }}
        unitTests: ${{ parameters.test }}
        functionalTests: ${{ parameters.test }}
        sign: ${{ parameters.sign }}
        verifySigning: ${{ parameters.sign }}
        publishArtifacts: ${{ parameters.publishArtifacts }}
        buildAlternatePackage: ${{ parameters.buildAlternatePackage }}

  # Windows (x86)
  - ${{ if and(parameters.win_x86, not(parameters.releaseRhelOnly)) }}:
    - template: build-jobs.yml
      parameters:
        jobName: build_windows_x86
        displayName: Windows (x86)
        pool:
          vmImage: windows-2019
        os: win
        arch: x86
        branch: ${{ parameters.branch }}
        componentDetection: false
        unitTests: ${{ parameters.test }}
        functionalTests: ${{ parameters.test }}
        sign: ${{ parameters.sign }}
        publishArtifacts: ${{ parameters.publishArtifacts }}
        buildAlternatePackage: ${{ parameters.buildAlternatePackage }}

  # Linux (x64)
  - ${{ if and(parameters.linux_x64, not(parameters.releaseRhelOnly)) }}:
    - template: build-jobs.yml
      parameters:
        jobName: build_linux_x64
        displayName: Linux (x64)
        pool:
          vmImage: ubuntu-20.04
        os: linux
        arch: x64
        branch: ${{ parameters.branch }}
        componentDetection: ${{ parameters.componentDetection }}
        unitTests: ${{ parameters.test }}
        functionalTests: ${{ parameters.test }}
        sign: ${{ parameters.sign }}
        publishArtifacts: ${{ parameters.publishArtifacts }}
        buildAlternatePackage: ${{ parameters.buildAlternatePackage }}

  # Linux (ARM)
  - ${{ if and(parameters.linux_arm, not(parameters.releaseRhelOnly)) }}:
    - template: build-jobs.yml
      parameters:
        jobName: build_linux_arm
        displayName: Linux (ARM)
        pool:
          vmImage: "ubuntu-20.04"
        timeoutInMinutes: 75
        os: linux
        arch: arm
        branch: ${{ parameters.branch }}
        componentDetection: false
        unitTests: false
        functionalTests: false
        sign: false
        publishArtifacts: ${{ parameters.publishArtifacts }}
        buildAlternatePackage: ${{ parameters.buildAlternatePackage }}

  # Linux (ARM64)
  - ${{ if and(parameters.linux_arm64, not(parameters.releaseRhelOnly)) }}:
    - template: build-jobs.yml
      parameters:
        jobName: build_linux_arm64
        displayName: Linux (ARM64)
        pool:
          name: 1ES_ARM_Agent_Pool
          vmImage: Ubuntu_2004_ARM64
        timeoutInMinutes: 75
        os: linux
        arch: arm64
        branch: ${{ parameters.branch }}
        componentDetection: false
        unitTests: ${{ parameters.test }}
        functionalTests: ${{ parameters.test }}
        sign: false
        publishArtifacts: ${{ parameters.publishArtifacts }}
        buildAlternatePackage: ${{ parameters.buildAlternatePackage }}

  # RHEL6 (x64)
  - ${{ if and(parameters.rhel6_x64, not(parameters.skipRhelRelease), parameters.releaseRhelOnly) }}:
    - template: build-jobs.yml
      parameters:
        jobName: build_rhel6_x64
        displayName: RHEL6 (x64)
        pool:
          vmImage: ubuntu-20.04
        container: dotnetcore_centos6
        os: rhel.6
        arch: x64
        branch: ${{ parameters.branch }}
        componentDetection: false
        unitTests: ${{ parameters.test }}
        functionalTests: ${{ parameters.test }}
        sign: false
        publishArtifacts: ${{ parameters.publishArtifacts }}
        buildAlternatePackage: ${{ parameters.buildAlternatePackage }}

  # macOS x64
  - ${{ if and(parameters.macOS_x64, not(parameters.releaseRhelOnly)) }}:
    - template: build-jobs.yml
      parameters:
        jobName: build_osx
        displayName: macOS (x64)
        pool:
          vmImage: macOS-11
        os: osx
        arch: x64
        branch: ${{ parameters.branch }}
        componentDetection: ${{ parameters.componentDetection }}
        unitTests: ${{ parameters.test }}
        functionalTests: ${{ parameters.test }}
        sign: ${{ parameters.sign }}
        publishArtifacts: ${{ parameters.publishArtifacts }}
        buildAlternatePackage: ${{ parameters.buildAlternatePackage }}

- ${{ parameters.postBuildStages }}
